name: Nix

on:
  push:
    branches-ignore: [ '_**' ]
  pull_request:
  workflow_dispatch:

jobs:
  nix:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build StarMalloc
        run: |
          nix build -L .#starmalloc
      - name: build StarMalloc logs
        run: |
          nix log .#starmalloc
      #- name: bench StarMalloc
      #  run: |
      #    nix build -L .#bench
      #- name: bench StarMalloc logs
      #  run: |
      #    nix log .#bench
