name: Nix

on:
  push:
    branches-ignore: [ '_**' ]
  pull_request:
  workflow_dispatch:

jobs:
  nix:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build StarMalloc (light)
        run: |
          nix build -L .#starmalloc-light
      - name: build StarMalloc (light) logs
        run: |
          nix log .#starmalloc-light

      - name: build StarMalloc
        run: |
          nix build -L .#starmalloc
      - name: build StarMalloc logs
        run: |
          nix log .#starmalloc

      - name: check dist/
        run: |
          nix build -L .#check-dist
      - name: check dist/ logs
        run: |
          nix log .#check-dist

      - name: check vendor/
        run: |
          nix build -L .#check-vendor
      - name: check vendor/ logs
        run: |
          nix log .#check-vendor

      #- name: bench StarMalloc
      #  run: |
      #    nix build -L .#bench
      #- name: bench StarMalloc logs
      #  run: |
      #    nix log .#bench
